#!/usr/bin/env bash
# PreToolUse hook: block direct edits to pixi.lock.
#
# pixi.lock is generated by `pixi install` / `pixi add` and editing it by hand
# is almost always a mistake. This hook reads the standard PreToolUse JSON
# from stdin, extracts tool_input.file_path, and exits 2 (block + feed stderr
# back to Claude) if the path looks like a pixi lockfile.

set -euo pipefail

input="$(cat)"
file_path="$(printf '%s' "$input" | jq -r '.tool_input.file_path // empty')"

case "$file_path" in
  ""|/dev/null) exit 0 ;;
  */pixi.lock|pixi.lock)
    echo "BLOCKED: pixi.lock is generated. Run 'pixi install' or 'pixi add <pkg>' instead of editing it directly." >&2
    exit 2
    ;;
esac

exit 0
